### ISSUE TITLE
Incorrect license definition

### ISSUE THREAD

**Issue by JamieMagee** [bagel897/pytoolconfig#11]
pdm throws a PEP621 validation for the license definition:

https://github.com/bagel897/pytoolconfig/blob/56d75a852791ca9bc75e859b99a9b91a5e6c1b1d/pyproject.toml#L5

[PEP621](https://peps.python.org/pep-0621/#license) shows it either needs to be:

```toml
license = { file = 'LICENSE' }
```

referring to the [`LICENSE` file](https://github.com/bagel897/pytoolconfig/blob/main/LICENSE) in this repo. Or

```toml
license = { text = 'LGPL-3.0-or-later' }
```

A valid [SPDX license identifier](https://spdx.org/licenses/). The `LGPL-3.0` identifier is deprecated. PEP621 explicitly mentions SPDX identifiers, not OSI identifiers, as suggested in #9.

**Comment by bagel897** [comment]
Thanks! I changed it back and did the text option
