### ISSUE TITLE
Packaging 1.2.5 failed

### ISSUE THREAD

**Issue by rhurlin** [bagel897/pytoolconfig#12]
Hi @bagel897,
A failure in the [publish](https://github.com/bagel897/pytoolconfig/actions/runs/3848258368/jobs/6555791062) process prevents the package from appearing at [PyPi](https://pypi.org/project/pytoolconfig/). Is the cause known and can 1.2.5 be expected to be published on PyPi after all?

Thanks for any explanation and answer.

Best wishes,
Rainer

**Comment by bagel897** [comment]
Whoops, forgot to manually publish. Fixed it now. My workflow usually doesn't work, I try to make it work each release.

**Comment by rhurlin** [comment]
Wow, that is a fast reaction. Many thanks!

Now I am able to update the FreeBSD port of [pytoolconfig](https://www.freshports.org/devel/py-pytoolconfig)   \o/
