### ISSUE TITLE
piplicenses does not recognize new license

### ISSUE THREAD

**Issue by i3rinkmann** [bagel897/pytoolconfig#13]
When i run: 
`python -m pipenv run python -m piplicenses --with-urls --order=license`
the Output is:
` pytoolconfig               1.2.5      UNKNOWN                                                  UNKNOWN`

as far as i understand the change from #9 was incorrect

@ecederstrand you mentioned piplicenses and i was wondering if you can show me how you tested it?

On https://spdx.org/licenses/ it only shows `LGPL-3.0-only` or `LGPL-3.0-or-later` to be OSI approved

<html>
<body>

Full name | Identifier | FSF Free/Libre? | OSI Approved?
-- | -- | -- | --
GNU Lesser General Public License v3.0 only | LGPL-3.0-only | Y | Y
GNU Lesser General Public License v3.0 or later | LGPL-3.0-or-later | Y | Y

</body>
</html>

**Comment by bagel897** [comment]
I may need to release a new version to reflect 9655177fa82329aa772bce34da25f1ee7f321dc9

**Comment by ecederstrand** [comment]
I should have added a reproducer and exact versions to #9 because I can't reproduce my issue any more. I agree that the latest version of pip-licenses now does not recognize the license of this package:

```bash
(tmp) % pip list
Package      Version
------------ -------
pip-licenses 4.1.0
pytoolconfig 1.2.5
[...]

(tmp) % pip-licenses --from=all
 Name          Version  License-Metadata  License-Classifier                   
 pytoolconfig  1.2.5    UNKNOWN           UNKNOWN                              
[...]
```
